name: Build and Deploy Project

on:
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Change if needed

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Generates build/ folder

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/  # Uploads built files

  deploy:
    needs: build  # Deploy runs after a successful build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: build/

      - name: Deploy to Server
        run: |
          scp -r build/* user@yourserver.com:/var/www/html/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
